from pathlib import Path
from app.services.email.template_renderer import EmailTemplateRenderer
from jinja2 import Environment, FileSystemLoader
from app.services.email.email_preview import EmailPreviewService

TEMPLATE_DIR = Path(__file__).resolve().parents[2] / "app" / "templates"


def get_environment():
    return Environment(
        loader=FileSystemLoader(TEMPLATE_DIR),
        autoescape=True,
    )


def test_base_html_template_loads():
    env = get_environment()
    template = env.get_template("email/base.html")

    assert template is not None


def test_base_text_template_loads():
    env = get_environment()
    template = env.get_template("email/base.txt")

    assert template is not None


def test_base_html_renders_branding_and_content():
    env = get_environment()

    html = env.get_template("email/base.html").render()

    assert "FieldOps" in html
    assert "FieldOps Notification" in html
    assert "Generated by FieldOps" in html


def test_base_html_renders_dynamic_values():
    env = get_environment()

    html = env.get_template("email/base.html").render(
        logo_url="https://example.com/logo.png",
        cta_url="https://example.com/job/123",
        cta_text="View Job",
        support_email="support@fieldops.io",
        unsubscribe_url="https://example.com/unsubscribe",
    )

    assert "https://example.com/logo.png" in html
    assert "https://example.com/job/123" in html
    assert "View Job" in html
    assert "support@fieldops.io" in html
    assert "https://example.com/unsubscribe" in html


def test_base_html_omits_optional_sections_when_values_missing():
    env = get_environment()

    html = env.get_template("email/base.html").render()

    assert 'class="brand-logo"' not in html
    assert 'class="cta-button"' not in html
    assert "mailto:" not in html
    assert "Unsubscribe" not in html


def test_base_text_renders_dynamic_values():
    env = get_environment()

    text = env.get_template("email/base.txt").render(
        cta_url="https://example.com/job/123",
        cta_text="View Job",
        support_email="support@fieldops.io",
        unsubscribe_url="https://example.com/unsubscribe",
    )

    assert "FieldOps" in text
    assert "View Job: https://example.com/job/123" in text
    assert "support@fieldops.io" in text
    assert "https://example.com/unsubscribe" in text


def test_base_text_omits_optional_sections_when_values_missing():
    env = get_environment()

    text = env.get_template("email/base.txt").render()

    assert "View Job:" not in text
    assert "support_email" not in text
    assert "unsubscribe_url" not in text


def test_base_html_contains_responsive_email_styles():
    env = get_environment()

    html = env.get_template("email/base.html").render()

    assert "max-width: 600px" in html
    assert "@media only screen and (max-width: 600px)" in html


def test_base_html_contains_dark_mode_support():
    env = get_environment()

    html = env.get_template("email/base.html").render()

    assert "@media (prefers-color-scheme: dark)" in html
    assert "supported-color-schemes" in html


def test_base_html_contains_accessible_email_structure():
    env = get_environment()

    html = env.get_template("email/base.html").render(
        logo_url="https://example.com/logo.png"
    )

    assert 'lang="en"' in html
    assert 'role="presentation"' in html
    assert 'alt=""' in html
    assert 'aria-hidden="true"' in html


def test_base_html_contains_cta_accessibility_attributes():
    env = get_environment()

    html = env.get_template("email/base.html").render(
        cta_url="https://example.com/job/123",
        cta_text="View Job",
    )

    assert 'target="_blank"' in html
    assert 'rel="noopener noreferrer"' in html


def test_base_html_has_jinja_blocks():
    template_source = (
        TEMPLATE_DIR / "email" / "base.html"
    ).read_text(encoding="utf-8")

    expected_blocks = [
        "title",
        "extra_styles",
        "header",
        "content",
        "heading",
        "body",
        "cta",
        "footer",
        "extra_body",
    ]

    for block in expected_blocks:
        assert f"block {block}" in template_source


def test_base_text_has_jinja_blocks():
    template_source = (
        TEMPLATE_DIR / "email" / "base.txt"
    ).read_text(encoding="utf-8")

    expected_blocks = [
        "title",
        "header",
        "content",
        "heading",
        "body",
        "cta",
        "footer",
    ]

    for block in expected_blocks:
        assert f"block {block}" in template_source


def test_base_html_escapes_dynamic_content():
    env = get_environment()

    html = env.get_template("email/base.html").render(
        cta_url="https://example.com",
        cta_text="<script>alert('x')</script>",
    )

    assert "<script>alert('x')</script>" not in html
    assert "&lt;script&gt;" in html


def test_child_template_inherits_base_layout(tmp_path):
    child_template = """
{% extends "email/base.html" %}

{% block title %}
Job Confirmation
{% endblock %}

{% block heading %}
Your Job Is Confirmed
{% endblock %}

{% block body %}
Your service job has been successfully confirmed.
{% endblock %}
"""

    child_path = tmp_path / "job_confirmation.html"
    child_path.write_text(child_template, encoding="utf-8")

    env = Environment(
        loader=FileSystemLoader(
            [
                TEMPLATE_DIR,
                tmp_path,
            ]
        ),
        autoescape=True,
    )

    html = env.get_template("job_confirmation.html").render(
        cta_url="https://example.com/job/123",
        cta_text="View Job",
    )

    # Child content
    assert "Job Confirmation" in html
    assert "Your Job Is Confirmed" in html
    assert "Your service job has been successfully confirmed." in html

    # Inherited base layout
    assert "FieldOps" in html
    assert "Generated by FieldOps" in html
    assert 'class="email-container"' in html

from app.services.email.template_renderer import EmailTemplateRenderer


def test_email_template_renderer_returns_html_and_text(tmp_path):
    child_template = """
{% extends "email/base.html" %}

{% block title %}
Job Confirmed
{% endblock %}

{% block heading %}
Job Confirmed
{% endblock %}

{% block body %}
Your job has been confirmed.
{% endblock %}
"""

    child_path = tmp_path / "renderer_test.html"
    child_path.write_text(child_template, encoding="utf-8")

    renderer = EmailTemplateRenderer(
        template_dir=[tmp_path, TEMPLATE_DIR]
    )

    result = renderer.render("renderer_test.html")

    assert result.html
    assert result.text

    assert "FieldOps" in result.html
    assert "Job Confirmed" in result.html
    assert "Your job has been confirmed." in result.html

    assert "FieldOps" in result.text
    assert "Job Confirmed" in result.text
    assert "Your job has been confirmed." in result.text


def test_email_template_renderer_inlines_css():
    renderer = EmailTemplateRenderer()

    result = renderer.render(
        "email/base.html",
        cta_url="https://example.com/job/123",
        cta_text="View Job",
    )

    # Premailer should add inline styles to HTML elements.
    assert 'style="' in result.html

    # Responsive and dark-mode media queries are intentionally
    # preserved inside <style> for email-client support.
    assert "@media only screen and (max-width: 600px)" in result.html
    assert "@media (prefers-color-scheme: dark)" in result.html


def test_email_template_renderer_generates_plain_text_from_html(tmp_path):
    child_template = """
{% extends "email/base.html" %}

{% block title %}
Job Confirmed
{% endblock %}

{% block heading %}
Job Confirmed
{% endblock %}

{% block body %}
Your job has been confirmed.
{% endblock %}
"""

    child_path = tmp_path / "renderer_test.html"
    child_path.write_text(child_template, encoding="utf-8")

    renderer = EmailTemplateRenderer(
        template_dir=[tmp_path, TEMPLATE_DIR]
    )

    result = renderer.render(
        "renderer_test.html",
        cta_url="https://example.com/job/123",
        cta_text="View Job",
    )

    assert "Job Confirmed" in result.text
    assert "Your job has been confirmed." in result.text
    assert "View Job" in result.text
    assert "https://example.com/job/123" in result.text


def test_email_template_renderer_preserves_dynamic_values():
    renderer = EmailTemplateRenderer()

    result = renderer.render(
        "email/base.html",
        logo_url="https://example.com/logo.png",
        cta_url="https://example.com/job/123",
        cta_text="View Job",
        support_email="support@fieldops.io",
        unsubscribe_url="https://example.com/unsubscribe",
        preview_text="Your FieldOps job has been confirmed.",
    )

    assert "https://example.com/logo.png" in result.html
    assert "https://example.com/job/123" in result.html
    assert "View Job" in result.html
    assert "support@fieldops.io" in result.html
    assert "https://example.com/unsubscribe" in result.html
    assert "Your FieldOps job has been confirmed." in result.html

def test_email_preview_service_returns_preview():
    service = EmailPreviewService()

    preview = service.preview(
        "email/base.html",
        heading="Preview Test",
        body="This is a preview email.",
    )

    assert preview.template_name == "email/base.html"
    assert preview.html
    assert preview.text

    assert "FieldOps" in preview.html
    assert "FieldOps" in preview.text


def test_email_preview_service_preserves_rendered_content(tmp_path):
    child_template = """
{% extends "email/base.html" %}

{% block title %}
Preview Job
{% endblock %}

{% block heading %}
Preview Job Confirmed
{% endblock %}

{% block body %}
This job is ready for preview.
{% endblock %}
"""

    child_path = tmp_path / "preview_test.html"
    child_path.write_text(child_template, encoding="utf-8")

    renderer = EmailTemplateRenderer(
        template_dir=[tmp_path, TEMPLATE_DIR]
    )

    service = EmailPreviewService(renderer=renderer)

    preview = service.preview("preview_test.html")

    assert preview.template_name == "preview_test.html"

    assert "Preview Job Confirmed" in preview.html
    assert "This job is ready for preview." in preview.html

    assert "Preview Job Confirmed" in preview.text
    assert "This job is ready for preview." in preview.text


def test_email_preview_service_accepts_dynamic_values():
    service = EmailPreviewService()

    preview = service.preview(
        "email/base.html",
        logo_url="https://example.com/logo.png",
        cta_url="https://example.com/job/123",
        cta_text="View Job",
        support_email="support@fieldops.io",
        unsubscribe_url="https://example.com/unsubscribe",
        preview_text="Your job is ready.",
    )

    assert "https://example.com/logo.png" in preview.html
    assert "https://example.com/job/123" in preview.html
    assert "View Job" in preview.html
    assert "support@fieldops.io" in preview.html
    assert "https://example.com/unsubscribe" in preview.html
    assert "Your job is ready." in preview.html


def test_child_template_inherits_base_template(tmp_path):
    template_dir = tmp_path / "email"
    template_dir.mkdir()

    base_template = template_dir / "base.html"
    child_template = template_dir / "job_confirmation.html"

    base_template.write_text(
        """
        <!DOCTYPE html>
        <html>
        <body>
            <header>
                {% block header %}FieldOps{% endblock %}
            </header>

            <main>
                {% block content %}
                <h1>{% block heading %}FieldOps Notification{% endblock %}</h1>
                {% block body %}Default body{% endblock %}
                {% endblock %}
            </main>
        </body>
        </html>
        """,
        encoding="utf-8",
    )

    child_template.write_text(
        """
        {% extends "base.html" %}

        {% block heading %}
        Job Confirmation
        {% endblock %}

        {% block body %}
        Your job has been confirmed.
        {% endblock %}
        """,
        encoding="utf-8",
    )

    from jinja2 import Environment, FileSystemLoader

    env = Environment(
        loader=FileSystemLoader(str(template_dir)),
        autoescape=True,
    )

    template = env.get_template("job_confirmation.html")

    rendered = template.render()

    assert "FieldOps" in rendered
    assert "Job Confirmation" in rendered
    assert "Your job has been confirmed." in rendered
    assert "Default body" not in rendered


def test_child_template_can_override_header_and_content(tmp_path):
    template_dir = tmp_path / "email"
    template_dir.mkdir()

    (template_dir / "base.html").write_text(
        """
        <html>
        <body>
            {% block header %}FieldOps{% endblock %}

            {% block content %}
            <h1>{% block heading %}Default Heading{% endblock %}</h1>
            {% block body %}Default Body{% endblock %}
            {% endblock %}
        </body>
        </html>
        """,
        encoding="utf-8",
    )

    (template_dir / "custom.html").write_text(
        """
        {% extends "base.html" %}

        {% block header %}
        Custom Header
        {% endblock %}

        {% block heading %}
        Custom Heading
        {% endblock %}

        {% block body %}
        Custom Body
        {% endblock %}
        """,
        encoding="utf-8",
    )

    from jinja2 import Environment, FileSystemLoader

    env = Environment(
        loader=FileSystemLoader(str(template_dir)),
        autoescape=True,
    )

    rendered = env.get_template("custom.html").render()

    assert "Custom Header" in rendered
    assert "Custom Heading" in rendered
    assert "Custom Body" in rendered
    assert "FieldOps" not in rendered
    assert "Default Heading" not in rendered
    assert "Default Body" not in rendered