import json
import logging
from datetime import datetime, timezone
from typing import Optional

logger = logging.getLogger(__name__)


def publish_dispatch_event(
    redis_client,
    event_type: str,
    job_id: str,
    old_status: str,
    new_status: str,
    tenant_id: str,
    technician_id: Optional[str] = None,
    technician_name: Optional[str] = None,
    completed_at: Optional[datetime] = None,
    correlation_id: Optional[str] = None,
    event_id: Optional[str] = None,
):
    """
    Publish a canonical dispatch event after successful persistence.

    For completion events, completed_at is the authoritative timestamp
    generated by the JobStatusMachine.

    event_id is deterministic for a persisted completion so downstream
    consumers have a stable idempotency key.
    """
    if not redis_client:
        logger.warning(
            "Redis client unavailable; skipping dispatch event publish."
        )
        return

    if completed_at is not None:
        if completed_at.tzinfo is None:
            raise ValueError("completed_at must be timezone-aware")

        timestamp = (
            completed_at
            .astimezone(timezone.utc)
            .isoformat()
            .replace("+00:00", "Z")
        )
    else:
        timestamp = (
            datetime.now(timezone.utc)
            .isoformat()
            .replace("+00:00", "Z")
        )

    event_id = event_id or f"{event_type}:{tenant_id}:{job_id}"

    payload = {
        # Keep legacy key for existing WebSocket consumers.
        "event": event_type,

        # Canonical event contract.
        "event_type": event_type.lower(),
        "event_id": event_id,
        "job_id": str(job_id),
        "old_status": old_status,
        "new_status": new_status,
        "timestamp": timestamp,
        "tenant_id": str(tenant_id),
    }

    if correlation_id:
        payload["correlation_id"] = correlation_id

    if technician_id and technician_name:
        payload["technician"] = {
            "tech_id": technician_id,
            "name": technician_name,
        }

    try:
        redis_client.publish(
            "dispatch_events",
            json.dumps(payload),
        )

        logger.info(
            "Published %s for job %s to dispatch_events channel.",
            event_type,
            job_id,
        )

    except Exception as e:
        logger.error(
            "Failed to publish dispatch event to Redis: %s",
            e,
        )